version: "3.7"
services:
  hanko-migrate:
    image: ghcr.io/teamhanko/hanko:main
    volumes:
      - type: bind
        source: ./config.yaml
        target: /etc/config/config.yaml
    command: --config /etc/config/config.yaml migrate up
    restart: on-failure
    depends_on:
      - postgresd
    networks:
      - intranet
  hanko:
    depends_on:
      - hanko-migrate
    image: ghcr.io/teamhanko/hanko:main
    ports:
      - '8000:8000' # public
      - '8001:8001' # private
    restart: unless-stopped
    command: serve --config /etc/config/config.yaml all
    volumes:
      - type: bind
        source: ./config.yaml
        target: /etc/config/config.yaml
    networks:
      - intranet
  postgresd:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hanko
      - POSTGRES_PASSWORD=hanko
      - POSTGRES_DB=hanko
    networks:
      - intranet
  hankojs:
    build: ../../hanko-js
    ports:
      - "9500:80"
    networks:
      - intranet
  example:
    build: ../../example
    ports:
      - "8888:8080"
    networks:
      - intranet
  mailslurper:
    image: marcopas/docker-mailslurper:latest
    ports:
      - '8080:8080' # web UI
      - '8085:8085'
    networks:
      - intranet
networks:
  intranet:
